### ISSUE TITLE
The program has been in the Starting patching the game for a long time

### ISSUE THREAD

**Issue by MrLinJingxing** [OssieFromDK/DeadByDaylight-Unlocker#10]
Starting patching the game..  
It has been executing for two or three hours but there is still no response. What is the likely cause? How can I fix this problem?

**Comment by OssieFromDK** [comment]
> Starting patching the game..  
> 
> It has been executing for two or three hours but there is still no response. What is the likely cause? How can I fix this problem?

Please join the discord - link in readme, and look under #common-errors. There is way to much stuff to post here.
