### ISSUE TITLE
安装完证书进入游戏后，提示网络连接错误

### ISSUE THREAD

**Issue by maorenyi96** [OssieFromDK/DeadByDaylight-Unlocker#18]
![image](https://github.com/OssieFromDK/DeadByDaylight-Unlocker/assets/79681734/8ecf7e15-0f76-4258-90e4-77ee8a2a10e3)

**Comment by maorenyi96** [comment]
After the certificate is installed, a message is displayed indicating a network connection error

**Comment by OssieFromDK** [comment]
> After the certificate is installed, a message is displayed indicating a network connection error

If you are playing ok steam a SSL Bypass is required to use the unlocker. We provide one at https://shoppy.gg/@FortniteBurger

**Comment by maorenyi96** [comment]
Is there any payment method that can be used in China

**Comment by OssieFromDK** [comment]
> Is there any payment method that can be used in China

I don't know, I am not Chinese, I am not familiar with your payment methods, you can go on the discord and ask if someone can purchase a license for you perhaps.
