### ISSUE TITLE
Help me build project

### ISSUE THREAD

**Issue by Soi9x** [OssieFromDK/DeadByDaylight-Unlocker#20]
hello, how can I use SteamWork.NET dll, I installed it from nuget but can't launch it: System.IO.FileNotFoundException: 'Could not load file or assembly 'Steamworks.NET, Version= 20.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.' , Need help.

**Comment by OssieFromDK** [comment]
> hello, how can I use SteamWork.NET dll, I installed it from nuget but can't launch it: System.IO.FileNotFoundException: 'Could not load file or assembly 'Steamworks.NET, Version= 20.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.' , Need help.

I don't remember where I got it from. Its used for debugging with Steamworks, I think there is a guide on steams website
