### ISSUE TITLE
SSL Bypass

### ISSUE THREAD

**Issue by 1147905189** [OssieFromDK/DeadByDaylight-Unlocker#22]
Unable to purchase

**Comment by 1147905189** [comment]
![Uploading {68CB9C43-4498-42e7-BE70-C1C3E26E8ACF}.png…]()

**Comment by 1147905189** [comment]
![{68CB9C43-4498-42e7-BE70-C1C3E26E8ACF}](https://github.com/OssieFromDK/DeadByDaylight-Unlocker/assets/134503058/55f80c1b-4075-4d28-ad20-b32f9f118697)

**Comment by 1147905189** [comment]
Because I am unable to bypass SSL, I am unable to connect to the network

**Comment by 1147905189** [comment]
There is another issue, clicking on pak bypass will display the creation of mods, but it will be automatically deleted immediately. The pop-up CMD box will disappear instantly

**Comment by OssieFromDK** [comment]
Use discord for help
