### ISSUE TITLE
Publishing Error

### ISSUE THREAD

**Issue by yourmomlover** [OssieFromDK/DeadByDaylight-Unlocker#34]
whenever i try to publish , just like shown in the readme i get this error 
![Screenshot 2024-08-29 113529](https://github.com/user-attachments/assets/2c263138-09d9-469a-b541-b263508f2135)
![Screenshot 2024-08-29 113536](https://github.com/user-attachments/assets/26a79344-5ce1-4d41-9ee2-abd23be6bb6a)

**Comment by OssieFromDK** [comment]
> whenever i try to publish , just like shown in the readme i get this error 
> 
> ![Screenshot 2024-08-29 113529](https://github.com/user-attachments/assets/2c263138-09d9-469a-b541-b263508f2135)
> 
> ![Screenshot 2024-08-29 113536](https://github.com/user-attachments/assets/26a79344-5ce1-4d41-9ee2-abd23be6bb6a)
> 
> 

Yes, you need to purchase FiddlerCore from Telerik
