### ISSUE TITLE
no network connection

### ISSUE THREAD

**Issue by XLunar** [OssieFromDK/DeadByDaylight-Unlocker#4]
![image_2023-10-31_174225461](https://github.com/OssieFromDK/DeadByDaylight-Unlocker/assets/149539550/b50bcf42-f00b-4082-874c-b8b2c7679cf2)

I launch it and it works but I cant load into to dbd

**Comment by OssieFromDK** [comment]
Which platform are you on?

**Comment by VioletFantasy** [comment]
Ive been having the same issue on Epic Games. If I manage to get into a match it is usually fine, but waiting for a match, logging in, loading the post game chat, etc, can have this issue quite often. Most often it occurs when Im waiting for a match but this could be because thats just where I am the longest.

Either way, love the project and hope you continue to improve it at your own pace! ^^

**Comment by Rym-bek** [comment]
hello, thanks for useful tool, but i have the same issue when i try to log in into game, i play dbd on **Steam** and also i tried using pakbypass but i get this error:

![image](https://github.com/OssieFromDK/DeadByDaylight-Unlocker/assets/91866986/e5b4a7b9-701b-4c44-b110-4b2f2e379cf2)

**Comment by Rym-bek** [comment]
hello, thanks for useful tool, but i have the same issue when i try to log in into game, i play dbd on Steam and also i tried using pakbypass but i get this error:

![image](https://github.com/OssieFromDK/DeadByDaylight-Unlocker/assets/91866986/78d236b1-8684-4f1d-8a39-840239ed74f1)

**Comment by OssieFromDK** [comment]
> hello, thanks for useful tool, but i have the same issue when i try to log in into game, i play dbd on Steam and also i tried using pakbypass but i get this error:
> 
> ![image](https://user-images.githubusercontent.com/91866986/279769762-78d236b1-8684-4f1d-8a39-840239ed74f1.png)

Hi, please go to your game files (<DBDLocation>/DeadByDaylight/Content/Paks), delete all paks higher than 348, verify the game on steam, then retry, also don't install mods before your first pak bypass and launch is complete.

If you don't understand the order of pak bypassing or something, I have made a [video guide](https://www.youtube.com/watch?v=NtGdlqMv-yE), or there is a written guide on the discord.

**Comment by OssieFromDK** [comment]
> Ive been having the same issue on Epic Games. If I manage to get into a match it is usually fine, but waiting for a match, logging in, loading the post game chat, etc, can have this issue quite often. Most often it occurs when Im waiting for a match but this could be because thats just where I am the longest.
> 
> Either way, love the project and hope you continue to improve it at your own pace! ^^

Hm, I will look into it, not sure what could be causing it tho, but I will check it out. Is it every time, and do you use mods?

**Comment by VioletFantasy** [comment]
> > Ive been having the same issue on Epic Games. If I manage to get into a match it is usually fine, but waiting for a match, logging in, loading the post game chat, etc, can have this issue quite often. Most often it occurs when Im waiting for a match but this could be because thats just where I am the longest.
> > Either way, love the project and hope you continue to improve it at your own pace! ^^
> 
> Hm, I will look into it, not sure what could be causing it tho, but I will check it out. Is it every time, and do you use mods?

No, I don't use any mods. I do also get an error relating to game version when loading the game using the tool though, but its pretty rare and I dont know how to reproduce it.

**Comment by OssieFromDK** [comment]
> [VioletFantasy](/VioletFantasy)

Hmm, thats weird, seems like you're the only one experiencing this.
Your AV isn't blocking connections? Could be the cause, since everything is funneled thru a proxy.
Also do you have the latest version? (3.6.3)

**Comment by OssieFromDK** [comment]
> No, I don't use any mods. I do also get an error relating to game version when loading the game using the tool though, but its pretty rare and I dont know how to reproduce it.
> 
> Edit: Its very often for the network issue though, like almost every time, and it will eventually happen even if I manage to finish a few matches.
> 
> Edit 2: Also get this error when trying to join a match. ![image](https://user-images.githubusercontent.com/149617408/279775302-a9090770-0bf7-4b95-9f2b-377bb118cf7a.png)

Hmm, thats weird, seems like you're the only one experiencing this.
Your AV isn't blocking connections? Could be the cause, since everything is funneled thru a proxy.
Also do you have the latest version? (3.6.3)

**Comment by XLunar** [comment]
> Which platform are you on?

steam lol

**Comment by OssieFromDK** [comment]
> steam lol


Try [this](https://github.com/OssieFromDK/DeadByDaylight-Unlocker/issues/4#issuecomment-1789472186)

**Comment by Xilencee** [comment]
> > > Ive been having the same issue on Epic Games. If I manage to get into a match it is usually fine, but waiting for a match, logging in, loading the post game chat, etc, can have this issue quite often. Most often it occurs when Im waiting for a match but this could be because thats just where I am the longest.
> > > Either way, love the project and hope you continue to improve it at your own pace! ^^
> > 
> > 
> > Hm, I will look into it, not sure what could be causing it tho, but I will check it out. Is it every time, and do you use mods?
> 
> No, I don't use any mods. I do also get an error relating to game version when loading the game using the tool though, but its pretty rare and I dont know how to reproduce it.
> 
> Edit: Its very often for the network issue though, like almost every time, and it will eventually happen even if I manage to finish a few matches.
> 
> Edit 2: Also get this error when trying to join a match. ![image](https://user-images.githubusercontent.com/149617408/279775302-a9090770-0bf7-4b95-9f2b-377bb118cf7a.png)

how did u get around the network error when opening the game

**Comment by VioletFantasy** [comment]
> > > > Ive been having the same issue on Epic Games. If I manage to get into a match it is usually fine, but waiting for a match, logging in, loading the post game chat, etc, can have this issue quite often. Most often it occurs when Im waiting for a match but this could be because thats just where I am the longest.
> > > > Either way, love the project and hope you continue to improve it at your own pace! ^^
> > > 
> > > 
> > > Hm, I will look into it, not sure what could be causing it tho, but I will check it out. Is it every time, and do you use mods?
> > 
> > 
> > No, I don't use any mods. I do also get an error relating to game version when loading the game using the tool though, but its pretty rare and I dont know how to reproduce it.
> > Edit: Its very often for the network issue though, like almost every time, and it will eventually happen even if I manage to finish a few matches.
> > Edit 2: Also get this error when trying to join a match. ![image](https://user-images.githubusercontent.com/149617408/279775302-a9090770-0bf7-4b95-9f2b-377bb118cf7a.png)
> 
> how did u get around the network error when opening the game. i cant even go into online

It's pretty random for me, sometimes its on opening the game, sometimes when looking for a match, sometimes during/after a match. The inconsistent part is how long it takes for the error (or similar) to occur.

**Comment by OssieFromDK** [comment]
Try the new update, and report if anything is changed.

**Comment by OssieFromDK** [comment]
Try the newest update, should fix the random network issues.
