### ISSUE TITLE
pak not working

### ISSUE THREAD

**Issue by Xilencee** [OssieFromDK/DeadByDaylight-Unlocker#5]
![Screenshot 2023-11-02 112144](https://github.com/OssieFromDK/DeadByDaylight-Unlocker/assets/149705481/9c019e22-4341-4c2d-8d68-de2242b6df3b)
everytime i selected the dead by daylight egs  shipping exe it says failed and will not work

**Comment by OssieFromDK** [comment]
> 
> 
> ![Screenshot 2023-11-02 112144](https://github.com/OssieFromDK/DeadByDaylight-Unlocker/assets/149705481/9c019e22-4341-4c2d-8d68-de2242b6df3b)
> 
> everytime i selected the dead by daylight egs  shipping exe it says failed and will not work
> 
> 

Don't have dead by daylight running. Also have steam open and your AV turned off.
