### ISSUE TITLE
Doesnt start 

### ISSUE THREAD

**Issue by Arias4412** [OssieFromDK/DeadByDaylight-Unlocker#6]
hey i follow the steps on usage after i load nothing hapend i cant install dbd to driver c: i install it in driver D has it anithing to do with this ?

**Comment by OssieFromDK** [comment]
> hey i follow the steps on usage after i load nothing hapend i cant install dbd to driver c: i install it in driver D has it anithing to do with this ?

What platform are you on? (Steam/Epic/MS)

**Comment by Arias4412** [comment]
Steam i start the exe (as admin) use the pypass choose the profile and launch then the exe close and nothing happend

**Comment by OssieFromDK** [comment]
> Steam i start the exe (as admin) use the pypass choose the profile and launch then the exe close and nothing happend

Is you AV turned off?

**Comment by Arias4412** [comment]
yes av is turned off

**Comment by OssieFromDK** [comment]
Does the tool itself crash or what happens?

**Comment by Arias4412** [comment]
yes after i press launch the tool crashes and nothing happend and there dont show a window with the security warning

**Comment by OssieFromDK** [comment]
Are you sure your anti virus is completely off? Also make sure to allow in firewall if you have that on your PC.

**Comment by VioletFantasy** [comment]
> Are you sure your anti virus is completely off? Also make sure to allow in firewall if you have that on your PC.

Seems fixed for me with the update for me. Played for a good few matches with no issues. I'll update if that changes, but for now it's working near perfectly. <3
