### ISSUE TITLE
Nothing happens after clicking launch

### ISSUE THREAD

**Issue by 6696969** [OssieFromDK/DeadByDaylight-Unlocker#7]
i choose all options right and click the launch. The window disappear and nothing pops up. The version is 3.6.5.1. Can you help me with this problem?

**Comment by OssieFromDK** [comment]
Turn off your AV completely.

**Comment by 6696969** [comment]
yeah only windows defender. And i totally turn if off

**Comment by OssieFromDK** [comment]
> yeah only windows defender. And i totally turn if off

Which platform?

**Comment by 6696969** [comment]
Egs

**Comment by 6696969** [comment]
> > yeah only windows defender. And i totally turn if off
> 
> Which platform?

egs

**Comment by OssieFromDK** [comment]
> > > yeah only windows defender. And i totally turn if off
> 
> > 
> 
> > Which platform?
> 
> 
> 
> egs

Turn off windows defender completely. Also allow the proccess in firewall. If still doesn't work, idk, go to the discord someone might have a solution

**Comment by 6696969** [comment]
> > > > yeah only windows defender. And i totally turn if off
> > 
> > 
> > > 
> > 
> > 
> > > Which platform?
> > 
> > 
> > egs
> 
> Turn off windows defender completely. Also allow the proccess in firewall. If still doesn't work, idk, go to the discord someone might have a solution

Tho it still doesn't work. Anyway thank you for your help
