### ISSUE TITLE
你好 好像不能进入游戏大厅

### ISSUE THREAD

**Issue by gantanhao66** [OssieFromDK/DeadByDaylight-Unlocker#9]
Hello, I was unable to start the game using the previous version. The new version can now start the game, but when I enter, I am prompted to access this content and need a network connection before accessing it. I can play games when I start the game normally

I am in the Chinese region==

**Comment by OssieFromDK** [comment]
Did you complete the Pak Bypass correctly? There is a guide on the discord or there is a [video](https://www.youtube.com/watch?v=NtGdlqMv-yE).

**Comment by gantanhao66** [comment]
After I entered Y and selected the win64exe file for the game, I was prompted

Please, put your custom mods in the 'Mods' folder

**Comment by OssieFromDK** [comment]
Did you download the correct version?, you need to download the  release from [here](https://github.com/OssieFromDK/DeadByDaylight-Unlocker/releases/tag/3.6.6.1). If you manually cloned it, you will need to build it yourself. The tool will auto add mods, only if you do manual pak bypass will you have to add mods manually.

**Comment by gantanhao66** [comment]
I am using the latest version 3.6.6.1
I seem to know what caused it

When my administrator starts fortnite, using Pak Bypass will prompt me

-------------

Custom mods detected Processing with the patching process

Preparing to patch the game

Game version: DeadByDaylight Win64 Shipping. exe

Failed to download NATO.sys

Please press any key to continue

--------------

He doesn't seem to have installed the driver, is it because the Fortnite started by the administrator cannot start Pak Bypass in administrator mode? After I find the file in the cache folder and manually start it, I will be prompted

Please place your custom module in the 'Mods' folder



I also made a game modifier, but I want to use DLC haha

**Comment by OssieFromDK** [comment]
Don't manually find and start the pak bypass, the one started from within fortnite burger is the correct one. If you are experiencing the Nato.sys error do the following:

Download [this](https://cdn.discordapp.com/attachments/927606625802539068/1145437586685444218/NATO.reg) file. Run it, then restart your computer. If you still encounter the error, try using a VPN, as your ispn, might be blocked from the external site. Also make sure not to have some AV on, that blocks connections.

**Comment by gantanhao66** [comment]
Thank you very much! I successfully entered the game. Thank you very much for your development

I may also put my program on Github in the future, even though I'm a novice haha
